version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
  install:
    runtime-versions:
      java: corretto8      
artifacts:
  files:
    - target/webUI-1.0.war